spring:
  application:
    name: NotificationService
  profiles:
    active: dev
  main:
    banner-mode: OFF
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
  flyway:
    enabled: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8081
  servlet:
    context-path: /notification-service

rest:
  security:
    enabled: true
    cors:
      allowed-origins: "*"
      allowed-headers: "*"
      allowed-methods: GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS
      max-age: 3600

smtp:
  host: emails
  port: 1025
  auth: false
  tls-enabled: false
  debug: true